/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import javax.swing.DefaultListModel;

/**
 *
 * @author Laider
 */
public class frmCine extends javax.swing.JFrame {
    DefaultListModel modeloGeneral = new DefaultListModel();
    DefaultListModel modeloMenores = new DefaultListModel();
    /**
     * Creates new form frmCine
     */
    public frmCine() {
        initComponents();
        lstGeneral.setModel(modeloGeneral);
        lstNiños.setModel(modeloMenores);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDias = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstGeneral = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstNiños = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rbtnGeneral = new javax.swing.JRadioButton();
        rbtnNiño = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        lblMNiños = new javax.swing.JLabel();
        lblMtotal = new javax.swing.JLabel();
        lblMgeneral = new javax.swing.JLabel();
        btnNiños = new javax.swing.JButton();
        btnGeneral = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cine");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Niños");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 50, -1));

        jLabel2.setText("Día");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 30, -1));

        jLabel3.setText("General");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 60, -1));

        lstDias.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstDias);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 190, -1));

        jScrollPane2.setViewportView(lstGeneral);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 180, -1));

        jScrollPane3.setViewportView(lstNiños);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 160, -1));

        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 90, -1));

        grupo1.add(rbtnGeneral);
        rbtnGeneral.setText("General");

        grupo1.add(rbtnNiño);
        rbtnNiño.setText("Niño");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnNiño)
                    .addComponent(rbtnGeneral))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnGeneral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnNiño)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 60));

        jButton1.setText("Procesar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        lblMNiños.setText("Monto Niños:");
        getContentPane().add(lblMNiños, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, -1, -1));

        lblMtotal.setText("Monto Total:");
        getContentPane().add(lblMtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));

        lblMgeneral.setText("Monto General:");
        getContentPane().add(lblMgeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        btnNiños.setText(">");
        btnNiños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNiñosActionPerformed(evt);
            }
        });
        getContentPane().add(btnNiños, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        btnGeneral.setText("<");
        btnGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneralActionPerformed(evt);
            }
        });
        getContentPane().add(btnGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //variables
        int pGeneral,pMenores,precio;
        int posDia;
        posDia=lstDias.getSelectedIndex();
        //procesar
        if(rbtnGeneral.isSelected() && posDia==0){
        pGeneral=9; 
        modeloGeneral.addElement(pGeneral);
        }
        else if(rbtnGeneral.isSelected() && posDia==1){
            pGeneral=7;
           modeloGeneral.addElement(pGeneral); 
        }
        else if(rbtnGeneral.isSelected() && posDia==2){
            pGeneral=10;
           modeloGeneral.addElement(pGeneral);
        }
        else if(rbtnGeneral.isSelected() && posDia==3){
            pGeneral=10;
           modeloGeneral.addElement(pGeneral);
        }
        else if(rbtnGeneral.isSelected() && posDia==4){
            pGeneral=10;
           modeloGeneral.addElement(pGeneral);
        }
        else if(rbtnGeneral.isSelected() && posDia==5){
            pGeneral=12;
            modeloGeneral.addElement(pGeneral);
        }
        else if(rbtnGeneral.isSelected() && posDia==6){
            pGeneral=12;
            modeloGeneral.addElement(pGeneral);
        }
        else if(rbtnNiño.isSelected() && posDia==0){
           pGeneral=7;
           modeloMenores.addElement(pGeneral);
        }
        else if(rbtnNiño.isSelected() && posDia==1){
           pGeneral=7;
           modeloMenores.addElement(pGeneral);
        }
        else if(rbtnNiño.isSelected() && posDia==2){
           pGeneral=8;
           modeloMenores.addElement(pGeneral);
        }
        else if(rbtnNiño.isSelected() && posDia==3){
           pGeneral=8;
           modeloMenores.addElement(pGeneral);
        }
        else if(rbtnNiño.isSelected() && posDia==4){
           pGeneral=8;
           modeloMenores.addElement(pGeneral);
        }
        else if(rbtnNiño.isSelected() && posDia==5){
           pGeneral=9;
           modeloMenores.addElement(pGeneral);
        }
        else if(rbtnNiño.isSelected() && posDia==6){
           pGeneral=9;
           modeloMenores.addElement(pGeneral);
        }
        //SUMAR LBL GENERAL
        int suma=0;
        for (int i = 0; i < modeloGeneral.getSize(); i++){
        suma+=Integer.parseInt(modeloGeneral.getElementAt(i).toString());
        }
        lblMgeneral.setText("Monto General: "+suma);
        //SUMA LBL NIÑOS
        int sum=0;
        for (int i = 0; i < modeloMenores.getSize(); i++){
         sum+=Integer.parseInt(modeloMenores.getElementAt(i).toString());
        }
        lblMNiños.setText("Monto Niños: "+sum);
        //Monto total
        
        total=sum+suma;
        lblMtotal.setText("Monto Total: "+total);



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneralActionPerformed
        String nombre;
        int pos;
        nombre=lstNiños.getSelectedValue().toString();
        pos=lstNiños.getSelectedIndex();
        modeloGeneral.addElement(nombre);
        modeloMenores.removeElement(pos);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGeneralActionPerformed

    private void btnNiñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNiñosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNiñosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeneral;
    private javax.swing.JButton btnNiños;
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblMNiños;
    private javax.swing.JLabel lblMgeneral;
    private javax.swing.JLabel lblMtotal;
    private javax.swing.JList<String> lstDias;
    private javax.swing.JList<String> lstGeneral;
    private javax.swing.JList<String> lstNiños;
    private javax.swing.JRadioButton rbtnGeneral;
    private javax.swing.JRadioButton rbtnNiño;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
int total=0;
}
