/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import javax.swing.JOptionPane;

/**
 *
 * @author Laider
 */
public class frmPregunta1 extends javax.swing.JFrame {

    /**
     * Creates new form frmPregunta1
     */
    public frmPregunta1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtS = new javax.swing.JTextArea();
        txtProcesar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NÚMERO");
        jLabel1.setName(""); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));
        jLabel1.getAccessibleContext().setAccessibleName("");

        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 90, -1));

        txtS.setColumns(20);
        txtS.setRows(5);
        jScrollPane1.setViewportView(txtS);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 310, 170));

        txtProcesar.setText("Procesar");
        txtProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProcesarActionPerformed(evt);
            }
        });
        getContentPane().add(txtProcesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProcesarActionPerformed
        int u = 0;
        int d = 0;
        int c = 0;
        int num;
        int numero;

        txtS.setText("");

        num = Integer.parseInt(txtNumero.getText());
        numero = Integer.parseInt(txtNumero.getText());
        //procesar

        //declarar UNIDAD,DECEMA,CENTENA
        u = num % 10;
        num = num / 10;
        d = num % 10;
        num = num / 10;
        c = num % 10;

        if (d == c + 1 && u == d + 1 || d == u + 1 && c == d + 1) {
            ;
        } else {
            txtS.append("\n"+"Numero: " + numero + "\n");
            txtS.append("\n"+"Condicion: Las cifras no son consecutivas"+"\n");
            if (c < d && c < u && d < u) {

                txtS.append("\n"+"Numero: " + numero + "\n");
                txtS.append("\n"+"Condición: Las cifras estan en orden ascendente"+"\n");
            } else {
                ;
                if (u < d && u < c && d < c) {
                    txtS.append("\n"+"Numero: " + numero + "\n");
                    txtS.append("\n"+"Condición: Las cifras estan en orden descendente"+"\n");
                } else {
                    ;
                    if (numero <= 99) {
                        txtS.append("\n"+"Numero: " + numero + "\n");
                        txtS.append("\n"+"Condición: El numero debe ser positivo de 3 cifras"+"\n");
                    } else {
                        ;
                        if (numero > 999) {
                            txtS.append("\n"+"Numero: " + numero + "\n");
                            txtS.append("\n"+"Condición: El numero debe ser positivo de 3 cifras"+"\n");
                        } else {
                            ;
                        }
                    }
                }
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtProcesarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPregunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPregunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPregunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPregunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPregunta1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JButton txtProcesar;
    private javax.swing.JTextArea txtS;
    // End of variables declaration//GEN-END:variables

}
